#!/usr/bin/env python3
"""L51b: the power the supply dissipates in the chassis, MEASURED on today's
bench instead of the hypotheses of L30 / L41a (the user, 2026-10-09: «Rifare e
mostrarmela»).

Reads ../rete/tb_psu_rete.cir (genera_tb_psu.py, the load of ../carico.txt:
today's rails and the selector's coil) and writes tb_calore.cir: the same
circuit, the three steady states (regime_m10 / _nom / _p10: mains -10 % / nom /
+10 %, the music on, every coil of the state on), and instead of the waveforms
the AVERAGE over the last 0.5 s (1.5-2.0 s; the bench settles in TSS = 2 s, the
reservoirs at ~0.27 A in ~1 s) of:

  pt1, pt2     the power out of T1's and T2's secondaries (the sources behind
               the sense sources VT1a_sns, VT1b_sns, VT2_sns): everything the
               chassis gets from the windings, copper included;
  cu1, cu2     the copper of the secondaries (RT1_SEC_A*, RT2_SEC_A);
  dbr1, dbr2   the bridges (DD501a-d; DD503a-d and the Schottky DD504);
  reg1, reg2   U501 and U502 (+-15 V): input current x (in - out);
  reg3         U503 (VRELAY 12 V): the same;
  paud         the audio board as the bench loads it: v(vplus) x I_PIU +
               |v(vminus)| x I_MENO (IPLUS, IMINUS);
  pvr          what U503 hands on: v(vrelay_reg) x its output current - the
               coils, the selector, the rest, the micro, the 5 V line.

The transformer's IRON is not in the bench (an ideal source with a series R
and L): the estimate keeps it as an hypothesis, declared.

    /usr/bin/python3 genera_calore.py [--uscita <file>]   # tb_calore.cir next to itself
"""
import os
import re
import sys

QUI = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(QUI, "..", "rete", "tb_psu_rete.cir")
OUT = (sys.argv[sys.argv.index("--uscita") + 1] if "--uscita" in sys.argv
       else os.path.join(QUI, "tb_calore.cir"))

testo = open(SRC).read().splitlines()
k = testo.index(".control")
corpo, ctl = testo[:k], testo[k:]

# the three steady-state blocks, verbatim up to tran
casi = {}
i = 0
while i < len(ctl):
    m = re.match(r"\* ---- (regime_(?:m10|nom|p10)) ----$", ctl[i])
    if m:
        j = i
        while not ctl[j].startswith("tran "):
            j += 1
        casi[m.group(1)] = ctl[i:j + 1]
        i = j
    i += 1
if sorted(casi) != ["regime_m10", "regime_nom", "regime_p10"]:
    sys.exit("RIFIUTATO: non trovo i tre casi a regime in %s" % SRC)
for nome, b in casi.items():
    if b[-1] != "tran 20u 2 0 20u uic":
        sys.exit("RIFIUTATO: %s non finisce a 2 s (%s)" % (nome, b[-1]))


def num(pat):
    v = [ln for ln in corpo if re.match(pat, ln)]
    if len(v) != 1:
        sys.exit("RIFIUTATO: %r: %d righe" % (pat, len(v)))
    return v[0]


# the audio board's currents as the deck has them (no second copy of carico.txt)
I_PIU = float(re.search(r"pwl\(0 0 0\.5 ([\d.e-]+)\)", num(r"IPLUS ")).group(1))
I_MENO = float(re.search(r"pwl\(0 0 0\.5 ([\d.e-]+)\)", num(r"IMINUS ")).group(1))
R1 = float(num(r"RT1_SEC_Aa ").split()[3])
R2 = float(num(r"RT2_SEC_A ").split()[3])
num(r"XU501 raw_p vplus 0 ")
num(r"XU502 raw_m vminus 0 ")
num(r"XU503 raw_v vrelay_reg rly_ret ")

DIODI1 = ("dd501a", "dd501b", "dd501c", "dd501d")
DIODI2 = ("dd503a", "dd503b", "dd503c", "dd503d", "dd504")
NODI = {"dd501a": ("t1_sec_a", "raw_p"), "dd501b": ("t1_sec_b", "raw_p"),
        "dd501c": ("raw_m", "t1_sec_a"), "dd501d": ("raw_m", "t1_sec_b"),
        "dd503a": ("t2_sec_a", "rect_v"), "dd503b": ("t2_sec_b", "rect_v"),
        "dd503c": ("rly_ret", "t2_sec_a"), "dd503d": ("rly_ret", "t2_sec_b"),
        "dd504": ("rect_v", "raw_v")}
for d, (a, c) in NODI.items():
    num(r"%s %s %s " % (d.upper().replace("DD", "DD", 1)[:2] + d[2:], a, c))

SAVE = ("save all " + " ".join("@%s[id]" % d for d in DIODI1 + DIODI2)
        + " @b.xu501.bi[i] @b.xu502.bi[i] @b.xu503.bi[i] @b.xu503.bo[i]")
LET = [
    "let pt1 = v(t1_sec_aa_e)*i(vt1a_sns) + v(t1_sec_ab_e)*i(vt1b_sns)",
    "let pt2 = (v(t2_sec_a_e)-v(t2_sec_b))*i(vt2_sns)",
    "let cu1 = %g*(i(vt1a_sns)^2 + i(vt1b_sns)^2)" % R1,
    "let cu2 = %g*i(vt2_sns)^2" % R2,
    "let dbr1 = " + " + ".join("(v(%s)-v(%s))*@%s[id]" % (NODI[d][0], NODI[d][1], d) for d in DIODI1),
    "let dbr2 = " + " + ".join("(v(%s)-v(%s))*@%s[id]" % (NODI[d][0], NODI[d][1], d) for d in DIODI2),
    "let reg1 = (v(raw_p)-v(vplus))*@b.xu501.bi[i]",
    "let reg2 = (v(vminus)-v(raw_m))*@b.xu502.bi[i]",
    "let reg3 = (v(raw_v)-v(vrelay_reg))*@b.xu503.bi[i]",
    "let paud = v(vplus)*%g - v(vminus)*%g" % (I_PIU, I_MENO),
    "let pvr = (v(vrelay_reg)-v(rly_ret))*@b.xu503.bo[i]",
]
GRANDEZZE = ("pt1", "pt2", "cu1", "cu2", "dbr1", "dbr2", "reg1", "reg2", "reg3", "paud", "pvr")

righe = ["* L51b tb_calore - GENERATED by genera_calore.py from ../rete/tb_psu_rete.cir "
         "(the three steady states; averages over 1.5-2.0 s)"] + corpo[1:] + [".control", "set numdgt=15", SAVE]
for nome in ("regime_m10", "regime_nom", "regime_p10"):
    righe += casi[nome] + LET
    righe += ["meas tran %s avg %s from=1.5 to=2" % (g, g) for g in GRANDEZZE]
    righe += ["echo CALORE %s %s" % (nome, " ".join("%s=$&%s" % (g, g) for g in GRANDEZZE)),
              "destroy all"]
righe += [".endc", ".end"]
open(OUT, "w").write("\n".join(righe) + "\n")
print("scritto %s (I_PIU %g A, I_MENO %g A, R1 %g, R2 %g)" % (OUT, I_PIU, I_MENO, R1, R2))
